apiVersion: v1
kind: ConfigMap
metadata:
  name: fastfood-config
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_HOST: "{{ .Values.postgres.host }}"
  POSTGRES_DB_GESTAO: "{{ .Values.postgres.db }}"
  POSTGRES_PORT: "{{ .Values.postgres.port }}"
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:80"
  JWT_SECRET_KEY: "MinhaChaveSuperSecretaQueTemMaisDe32Caracteres123!"