{{- if not (lookup "v1" "Secret" .Release.Namespace "db-credentials-gestao") -}}
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-gestao
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.credentials.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.credentials.password | quote }}
{{- end -}}